# Generated by Django 4.1.4 on 2022-12-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('sobrenome', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
